// Code generated for microservices-course.
// Do not edit manually.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/yerkesh/inventory/internal/model"
)

// NewPartService creates a new instance of PartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartService {
	mock := &PartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartService is an autogenerated mock type for the PartService type
type PartService struct {
	mock.Mock
}

type PartService_Expecter struct {
	mock *mock.Mock
}

func (_m *PartService) EXPECT() *PartService_Expecter {
	return &PartService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type PartService
func (_mock *PartService) Get(ctx context.Context, rawUUID string) (model.Part, error) {
	ret := _mock.Called(ctx, rawUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return returnFunc(ctx, rawUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = returnFunc(ctx, rawUUID)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, rawUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - rawUUID string
func (_e *PartService_Expecter) Get(ctx interface{}, rawUUID interface{}) *PartService_Get_Call {
	return &PartService_Get_Call{Call: _e.mock.On("Get", ctx, rawUUID)}
}

func (_c *PartService_Get_Call) Run(run func(ctx context.Context, rawUUID string)) *PartService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartService_Get_Call) Return(part model.Part, err error) *PartService_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartService_Get_Call) RunAndReturn(run func(ctx context.Context, rawUUID string) (model.Part, error)) *PartService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type PartService
func (_mock *PartService) List(ctx context.Context, rawUUIDs []string, partType model.PartType) ([]model.Part, error) {
	ret := _mock.Called(ctx, rawUUIDs, partType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, model.PartType) ([]model.Part, error)); ok {
		return returnFunc(ctx, rawUUIDs, partType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, model.PartType) []model.Part); ok {
		r0 = returnFunc(ctx, rawUUIDs, partType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, model.PartType) error); ok {
		r1 = returnFunc(ctx, rawUUIDs, partType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PartService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - rawUUIDs []string
//   - partType model.PartType
func (_e *PartService_Expecter) List(ctx interface{}, rawUUIDs interface{}, partType interface{}) *PartService_List_Call {
	return &PartService_List_Call{Call: _e.mock.On("List", ctx, rawUUIDs, partType)}
}

func (_c *PartService_List_Call) Run(run func(ctx context.Context, rawUUIDs []string, partType model.PartType)) *PartService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 model.PartType
		if args[2] != nil {
			arg2 = args[2].(model.PartType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PartService_List_Call) Return(parts []model.Part, err error) *PartService_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartService_List_Call) RunAndReturn(run func(ctx context.Context, rawUUIDs []string, partType model.PartType) ([]model.Part, error)) *PartService_List_Call {
	_c.Call.Return(run)
	return _c
}
