// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип детали
type PartType int32

const (
	PartType_PART_TYPE_UNSPECIFIED PartType = 0
	PartType_PART_TYPE_HULL        PartType = 1
	PartType_PART_TYPE_ENGINE      PartType = 2
	PartType_PART_TYPE_SHIELD      PartType = 3
	PartType_PART_TYPE_WEAPON      PartType = 4
)

// Enum value maps for PartType.
var (
	PartType_name = map[int32]string{
		0: "PART_TYPE_UNSPECIFIED",
		1: "PART_TYPE_HULL",
		2: "PART_TYPE_ENGINE",
		3: "PART_TYPE_SHIELD",
		4: "PART_TYPE_WEAPON",
	}
	PartType_value = map[string]int32{
		"PART_TYPE_UNSPECIFIED": 0,
		"PART_TYPE_HULL":        1,
		"PART_TYPE_ENGINE":      2,
		"PART_TYPE_SHIELD":      3,
		"PART_TYPE_WEAPON":      4,
	}
)

func (x PartType) Enum() *PartType {
	p := new(PartType)
	*p = x
	return p
}

func (x PartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (PartType) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x PartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartType.Descriptor instead.
func (PartType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// Part представляет деталь космического корабля
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор детали
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Название детали
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Описание детали
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Цена в копейках (5000₽ = 500000)
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	PartType      PartType               `protobuf:"varint,5,opt,name=part_type,json=partType,proto3,enum=inventory.v1.PartType" json:"part_type,omitempty"`
	StockQuantity int64                  `protobuf:"varint,6,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Part) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Part) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Part) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Part) GetPartType() PartType {
	if x != nil {
		return x.PartType
	}
	return PartType_PART_TYPE_UNSPECIFIED
}

func (x *Part) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Part) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Запрос на получение детали по UUID
type GetPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartRequest) Reset() {
	*x = GetPartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartRequest) ProtoMessage() {}

func (x *GetPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartRequest.ProtoReflect.Descriptor instead.
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetPartRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetPartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Part          *Part                  `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartResponse) Reset() {
	*x = GetPartResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartResponse) ProtoMessage() {}

func (x *GetPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartResponse.ProtoReflect.Descriptor instead.
func (*GetPartResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetPartResponse) GetPart() *Part {
	if x != nil {
		return x.Part
	}
	return nil
}

type ListPartsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartType      PartType               `protobuf:"varint,1,opt,name=part_type,json=partType,proto3,enum=inventory.v1.PartType" json:"part_type,omitempty"`
	Uuids         []string               `protobuf:"bytes,2,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsRequest) Reset() {
	*x = ListPartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsRequest) ProtoMessage() {}

func (x *ListPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsRequest.ProtoReflect.Descriptor instead.
func (*ListPartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ListPartsRequest) GetPartType() PartType {
	if x != nil {
		return x.PartType
	}
	return PartType_PART_TYPE_UNSPECIFIED
}

func (x *ListPartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type ListPartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*Part                `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsResponse) Reset() {
	*x = ListPartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsResponse) ProtoMessage() {}

func (x *ListPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsResponse.ProtoReflect.Descriptor instead.
func (*ListPartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ListPartsResponse) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\x04Part\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x123\n" +
	"\tpart_type\x18\x05 \x01(\x0e2\x16.inventory.v1.PartTypeR\bpartType\x12%\n" +
	"\x0estock_quantity\x18\x06 \x01(\x03R\rstockQuantity\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"$\n" +
	"\x0eGetPartRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"9\n" +
	"\x0fGetPartResponse\x12&\n" +
	"\x04part\x18\x01 \x01(\v2\x12.inventory.v1.PartR\x04part\"]\n" +
	"\x10ListPartsRequest\x123\n" +
	"\tpart_type\x18\x01 \x01(\x0e2\x16.inventory.v1.PartTypeR\bpartType\x12\x14\n" +
	"\x05uuids\x18\x02 \x03(\tR\x05uuids\"=\n" +
	"\x11ListPartsResponse\x12(\n" +
	"\x05parts\x18\x01 \x03(\v2\x12.inventory.v1.PartR\x05parts*{\n" +
	"\bPartType\x12\x19\n" +
	"\x15PART_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePART_TYPE_HULL\x10\x01\x12\x14\n" +
	"\x10PART_TYPE_ENGINE\x10\x02\x12\x14\n" +
	"\x10PART_TYPE_SHIELD\x10\x03\x12\x14\n" +
	"\x10PART_TYPE_WEAPON\x10\x042\xa8\x01\n" +
	"\x10InventoryService\x12F\n" +
	"\aGetPart\x12\x1c.inventory.v1.GetPartRequest\x1a\x1d.inventory.v1.GetPartResponse\x12L\n" +
	"\tListParts\x12\x1e.inventory.v1.ListPartsRequest\x1a\x1f.inventory.v1.ListPartsResponseB>Z<github.com/yerkesh/shared/pkg/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(PartType)(0),                 // 0: inventory.v1.PartType
	(*Part)(nil),                  // 1: inventory.v1.Part
	(*GetPartRequest)(nil),        // 2: inventory.v1.GetPartRequest
	(*GetPartResponse)(nil),       // 3: inventory.v1.GetPartResponse
	(*ListPartsRequest)(nil),      // 4: inventory.v1.ListPartsRequest
	(*ListPartsResponse)(nil),     // 5: inventory.v1.ListPartsResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.Part.part_type:type_name -> inventory.v1.PartType
	6, // 1: inventory.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: inventory.v1.GetPartResponse.part:type_name -> inventory.v1.Part
	0, // 3: inventory.v1.ListPartsRequest.part_type:type_name -> inventory.v1.PartType
	1, // 4: inventory.v1.ListPartsResponse.parts:type_name -> inventory.v1.Part
	2, // 5: inventory.v1.InventoryService.GetPart:input_type -> inventory.v1.GetPartRequest
	4, // 6: inventory.v1.InventoryService.ListParts:input_type -> inventory.v1.ListPartsRequest
	3, // 7: inventory.v1.InventoryService.GetPart:output_type -> inventory.v1.GetPartResponse
	5, // 8: inventory.v1.InventoryService.ListParts:output_type -> inventory.v1.ListPartsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
