// Code generated for microservices-course.
// Do not edit manually.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/yerkesh/inventory/internal/model"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type Repository
func (_mock *Repository) Get(ctx context.Context, partUUID uuid.UUID) (model.Part, error) {
	ret := _mock.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Part, error)); ok {
		return returnFunc(ctx, partUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Part); ok {
		r0 = returnFunc(ctx, partUUID)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID uuid.UUID
func (_e *Repository_Expecter) Get(ctx interface{}, partUUID interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", ctx, partUUID)}
}

func (_c *Repository_Get_Call) Run(run func(ctx context.Context, partUUID uuid.UUID)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Get_Call) Return(part model.Part, err error) *Repository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(ctx context.Context, partUUID uuid.UUID) (model.Part, error)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Repository
func (_mock *Repository) List(ctx context.Context, partUUIDs []uuid.UUID, partType model.PartType) ([]model.Part, error) {
	ret := _mock.Called(ctx, partUUIDs, partType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, model.PartType) ([]model.Part, error)); ok {
		return returnFunc(ctx, partUUIDs, partType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, model.PartType) []model.Part); ok {
		r0 = returnFunc(ctx, partUUIDs, partType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, model.PartType) error); ok {
		r1 = returnFunc(ctx, partUUIDs, partType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUIDs []uuid.UUID
//   - partType model.PartType
func (_e *Repository_Expecter) List(ctx interface{}, partUUIDs interface{}, partType interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, partUUIDs, partType)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, partUUIDs []uuid.UUID, partType model.PartType)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 model.PartType
		if args[2] != nil {
			arg2 = args[2].(model.PartType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_List_Call) Return(parts []model.Part, err error) *Repository_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(ctx context.Context, partUUIDs []uuid.UUID, partType model.PartType) ([]model.Part, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}
