// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type CancelOrderBadRequest Error

func (*CancelOrderBadRequest) cancelOrderRes() {}

type CancelOrderConflict Error

func (*CancelOrderConflict) cancelOrderRes() {}

type CancelOrderInternalServerError Error

func (*CancelOrderInternalServerError) cancelOrderRes() {}

type CancelOrderNotFound Error

func (*CancelOrderNotFound) cancelOrderRes() {}

// Пустой ответ при успешной отмене (успех определяется
// кодом 200).
// Ref: #
type CancelOrderResponse struct{}

func (*CancelOrderResponse) cancelOrderRes() {}

type CreateOrderBadRequest Error

func (*CreateOrderBadRequest) createOrderRes() {}

type CreateOrderConflict Error

func (*CreateOrderConflict) createOrderRes() {}

type CreateOrderInternalServerError Error

func (*CreateOrderInternalServerError) createOrderRes() {}

type CreateOrderNotFound Error

func (*CreateOrderNotFound) createOrderRes() {}

// Ref: #
type CreateOrderRequest struct {
	// UUID корпуса (обязательный, v4).
	HullUUID uuid.UUID `json:"hull_uuid"`
	// UUID двигателя (обязательный, v4).
	EngineUUID uuid.UUID `json:"engine_uuid"`
	// UUID щита (опциональный, v4).
	ShieldUUID OptNilUUID `json:"shield_uuid"`
	// UUID вооружения (опциональный, v4).
	WeaponUUID OptNilUUID `json:"weapon_uuid"`
}

// GetHullUUID returns the value of HullUUID.
func (s *CreateOrderRequest) GetHullUUID() uuid.UUID {
	return s.HullUUID
}

// GetEngineUUID returns the value of EngineUUID.
func (s *CreateOrderRequest) GetEngineUUID() uuid.UUID {
	return s.EngineUUID
}

// GetShieldUUID returns the value of ShieldUUID.
func (s *CreateOrderRequest) GetShieldUUID() OptNilUUID {
	return s.ShieldUUID
}

// GetWeaponUUID returns the value of WeaponUUID.
func (s *CreateOrderRequest) GetWeaponUUID() OptNilUUID {
	return s.WeaponUUID
}

// SetHullUUID sets the value of HullUUID.
func (s *CreateOrderRequest) SetHullUUID(val uuid.UUID) {
	s.HullUUID = val
}

// SetEngineUUID sets the value of EngineUUID.
func (s *CreateOrderRequest) SetEngineUUID(val uuid.UUID) {
	s.EngineUUID = val
}

// SetShieldUUID sets the value of ShieldUUID.
func (s *CreateOrderRequest) SetShieldUUID(val OptNilUUID) {
	s.ShieldUUID = val
}

// SetWeaponUUID sets the value of WeaponUUID.
func (s *CreateOrderRequest) SetWeaponUUID(val OptNilUUID) {
	s.WeaponUUID = val
}

// Ref: #
type CreateOrderResponse struct {
	// UUID созданного заказа (v4).
	OrderUUID uuid.UUID `json:"order_uuid"`
	// Итоговая стоимость в копейках.
	TotalPrice int64 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() int64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val int64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #
type Error struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Человекочитаемое описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

type GetOrderBadRequest Error

func (*GetOrderBadRequest) getOrderRes() {}

type GetOrderInternalServerError Error

func (*GetOrderInternalServerError) getOrderRes() {}

type GetOrderNotFound Error

func (*GetOrderNotFound) getOrderRes() {}

// NewOptNilPaymentMethod returns new OptNilPaymentMethod with value set to v.
func NewOptNilPaymentMethod(v PaymentMethod) OptNilPaymentMethod {
	return OptNilPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptNilPaymentMethod is optional nullable PaymentMethod.
type OptNilPaymentMethod struct {
	Value PaymentMethod
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilPaymentMethod was set.
func (o OptNilPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilPaymentMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilPaymentMethod) SetToNull() {
	o.Set = true
	o.Null = true
	var v PaymentMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #
type OrderDto struct {
	// UUID заказа (v4).
	OrderUUID uuid.UUID `json:"order_uuid"`
	// UUID корпуса (v4).
	HullUUID uuid.UUID `json:"hull_uuid"`
	// UUID двигателя (v4).
	EngineUUID uuid.UUID `json:"engine_uuid"`
	// UUID щита (опциональный, v4).
	ShieldUUID OptNilUUID `json:"shield_uuid"`
	// UUID вооружения (опциональный, v4).
	WeaponUUID OptNilUUID `json:"weapon_uuid"`
	// Итоговая стоимость в копейках.
	TotalPrice int64 `json:"total_price"`
	// UUID транзакции (после оплаты, v4).
	TransactionUUID OptNilUUID `json:"transaction_uuid"`
	// Способ оплаты (после оплаты).
	PaymentMethod OptNilPaymentMethod `json:"payment_method"`
	Status        OrderStatus         `json:"status"`
	// Дата создания заказа.
	CreatedAt time.Time `json:"created_at"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *OrderDto) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetHullUUID returns the value of HullUUID.
func (s *OrderDto) GetHullUUID() uuid.UUID {
	return s.HullUUID
}

// GetEngineUUID returns the value of EngineUUID.
func (s *OrderDto) GetEngineUUID() uuid.UUID {
	return s.EngineUUID
}

// GetShieldUUID returns the value of ShieldUUID.
func (s *OrderDto) GetShieldUUID() OptNilUUID {
	return s.ShieldUUID
}

// GetWeaponUUID returns the value of WeaponUUID.
func (s *OrderDto) GetWeaponUUID() OptNilUUID {
	return s.WeaponUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderDto) GetTotalPrice() int64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderDto) GetTransactionUUID() OptNilUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderDto) GetPaymentMethod() OptNilPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *OrderDto) GetStatus() OrderStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *OrderDto) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetOrderUUID sets the value of OrderUUID.
func (s *OrderDto) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetHullUUID sets the value of HullUUID.
func (s *OrderDto) SetHullUUID(val uuid.UUID) {
	s.HullUUID = val
}

// SetEngineUUID sets the value of EngineUUID.
func (s *OrderDto) SetEngineUUID(val uuid.UUID) {
	s.EngineUUID = val
}

// SetShieldUUID sets the value of ShieldUUID.
func (s *OrderDto) SetShieldUUID(val OptNilUUID) {
	s.ShieldUUID = val
}

// SetWeaponUUID sets the value of WeaponUUID.
func (s *OrderDto) SetWeaponUUID(val OptNilUUID) {
	s.WeaponUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderDto) SetTotalPrice(val int64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderDto) SetTransactionUUID(val OptNilUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderDto) SetPaymentMethod(val OptNilPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *OrderDto) SetStatus(val OrderStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *OrderDto) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*OrderDto) getOrderRes() {}

// Статус заказа.
// Ref: #
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PayOrderBadRequest Error

func (*PayOrderBadRequest) payOrderRes() {}

type PayOrderConflict Error

func (*PayOrderConflict) payOrderRes() {}

type PayOrderInternalServerError Error

func (*PayOrderInternalServerError) payOrderRes() {}

type PayOrderNotFound Error

func (*PayOrderNotFound) payOrderRes() {}

// Ref: #
type PayOrderRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #
type PayOrderResponse struct {
	// UUID транзакции оплаты (v4).
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Способ оплаты.
// Ref: #
type PaymentMethod string

const (
	PaymentMethodCARD          PaymentMethod = "CARD"
	PaymentMethodSBP           PaymentMethod = "SBP"
	PaymentMethodCREDITCARD    PaymentMethod = "CREDIT_CARD"
	PaymentMethodINVESTORMONEY PaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodCARD,
		PaymentMethodSBP,
		PaymentMethodCREDITCARD,
		PaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodCARD:
		return []byte(s), nil
	case PaymentMethodSBP:
		return []byte(s), nil
	case PaymentMethodCREDITCARD:
		return []byte(s), nil
	case PaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodCARD:
		*s = PaymentMethodCARD
		return nil
	case PaymentMethodSBP:
		*s = PaymentMethodSBP
		return nil
	case PaymentMethodCREDITCARD:
		*s = PaymentMethodCREDITCARD
		return nil
	case PaymentMethodINVESTORMONEY:
		*s = PaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
