// Code generated for microservices-course.
// Do not edit manually.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/yerkesh/order/internal/model"
)

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Cancel(ctx context.Context, orderUUID uuid.UUID) error {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type OrderRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderRepository_Expecter) Cancel(ctx interface{}, orderUUID interface{}) *OrderRepository_Cancel_Call {
	return &OrderRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orderUUID)}
}

func (_c *OrderRepository_Cancel_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_Cancel_Call) Return(err error) *OrderRepository_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_Cancel_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) error) *OrderRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Create(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) Create(ctx interface{}, order interface{}) *OrderRepository_Create_Call {
	return &OrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *OrderRepository_Create_Call) Run(run func(ctx context.Context, order model.Order)) *OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_Create_Call) Return(err error) *OrderRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FinishPayment provides a mock function for the type OrderRepository
func (_mock *OrderRepository) FinishPayment(ctx context.Context, orderUUID uuid.UUID, transactionUUID uuid.UUID, method model.PaymentMethod) (model.Order, error) {
	ret := _mock.Called(ctx, orderUUID, transactionUUID, method)

	if len(ret) == 0 {
		panic("no return value specified for FinishPayment")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) (model.Order, error)); ok {
		return returnFunc(ctx, orderUUID, transactionUUID, method)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) model.Order); ok {
		r0 = returnFunc(ctx, orderUUID, transactionUUID, method)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, orderUUID, transactionUUID, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_FinishPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishPayment'
type OrderRepository_FinishPayment_Call struct {
	*mock.Call
}

// FinishPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
//   - transactionUUID uuid.UUID
//   - method model.PaymentMethod
func (_e *OrderRepository_Expecter) FinishPayment(ctx interface{}, orderUUID interface{}, transactionUUID interface{}, method interface{}) *OrderRepository_FinishPayment_Call {
	return &OrderRepository_FinishPayment_Call{Call: _e.mock.On("FinishPayment", ctx, orderUUID, transactionUUID, method)}
}

func (_c *OrderRepository_FinishPayment_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID, transactionUUID uuid.UUID, method model.PaymentMethod)) *OrderRepository_FinishPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 model.PaymentMethod
		if args[3] != nil {
			arg3 = args[3].(model.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OrderRepository_FinishPayment_Call) Return(order model.Order, err error) *OrderRepository_FinishPayment_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_FinishPayment_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID, transactionUUID uuid.UUID, method model.PaymentMethod) (model.Order, error)) *OrderRepository_FinishPayment_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Get(ctx context.Context, orderUUID uuid.UUID) (model.Order, error) {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(ctx, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderRepository_Expecter) Get(ctx interface{}, orderUUID interface{}) *OrderRepository_Get_Call {
	return &OrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, orderUUID)}
}

func (_c *OrderRepository_Get_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_Get_Call) Return(order model.Order, err error) *OrderRepository_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_Get_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) (model.Order, error)) *OrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPayment provides a mock function for the type OrderRepository
func (_mock *OrderRepository) ResetPayment(ctx context.Context, orderUUID uuid.UUID) error {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for ResetPayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_ResetPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPayment'
type OrderRepository_ResetPayment_Call struct {
	*mock.Call
}

// ResetPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderRepository_Expecter) ResetPayment(ctx interface{}, orderUUID interface{}) *OrderRepository_ResetPayment_Call {
	return &OrderRepository_ResetPayment_Call{Call: _e.mock.On("ResetPayment", ctx, orderUUID)}
}

func (_c *OrderRepository_ResetPayment_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderRepository_ResetPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_ResetPayment_Call) Return(err error) *OrderRepository_ResetPayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_ResetPayment_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) error) *OrderRepository_ResetPayment_Call {
	_c.Call.Return(run)
	return _c
}

// StartPayment provides a mock function for the type OrderRepository
func (_mock *OrderRepository) StartPayment(ctx context.Context, orderUUID uuid.UUID) (model.Order, error) {
	ret := _mock.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for StartPayment")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(ctx, orderUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_StartPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartPayment'
type OrderRepository_StartPayment_Call struct {
	*mock.Call
}

// StartPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderRepository_Expecter) StartPayment(ctx interface{}, orderUUID interface{}) *OrderRepository_StartPayment_Call {
	return &OrderRepository_StartPayment_Call{Call: _e.mock.On("StartPayment", ctx, orderUUID)}
}

func (_c *OrderRepository_StartPayment_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderRepository_StartPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_StartPayment_Call) Return(order model.Order, err error) *OrderRepository_StartPayment_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_StartPayment_Call) RunAndReturn(run func(ctx context.Context, orderUUID uuid.UUID) (model.Order, error)) *OrderRepository_StartPayment_Call {
	_c.Call.Return(run)
	return _c
}
