// Code generated for microservices-course.
// Do not edit manually.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/yerkesh/order/internal/model"
)

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type PaymentClient
func (_mock *PaymentClient) PayOrder(ctx context.Context, orderUUID string, method model.PaymentMethod) (uuid.UUID, error) {
	ret := _mock.Called(ctx, orderUUID, method)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) (uuid.UUID, error)); ok {
		return returnFunc(ctx, orderUUID, method)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.PaymentMethod) uuid.UUID); ok {
		r0 = returnFunc(ctx, orderUUID, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, orderUUID, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - method model.PaymentMethod
func (_e *PaymentClient_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, method interface{}) *PaymentClient_PayOrder_Call {
	return &PaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, method)}
}

func (_c *PaymentClient_PayOrder_Call) Run(run func(ctx context.Context, orderUUID string, method model.PaymentMethod)) *PaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(model.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PaymentClient_PayOrder_Call) Return(uUID uuid.UUID, err error) *PaymentClient_PayOrder_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *PaymentClient_PayOrder_Call) RunAndReturn(run func(ctx context.Context, orderUUID string, method model.PaymentMethod) (uuid.UUID, error)) *PaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
